### ISSUE TITLE
Backups of…

### ISSUE THREAD

**Issue by RyanRoberts** [johndturn/raycast-single-disk-eject#1]
Hey, thanks for the great plugin. I don't know if this is a bug or just how things work but is there any way to not show backup disks that macOS seems to create? See this screenshot https://media.yep.digital/iFGOdo

In fact I have no idea where they come from but I'm assuming it's Time machine.

**Comment by johndturn** [comment]
@RyanRoberts So sorry, I missed that you opened this issue earlier. 

I've got a feature coming out shortly. Follow it here: https://github.com/raycast/extensions/issues/2283

I'll close in favor of that issue in the main Extensions repo where the update will be merged. However, if I've interpreted your request wrong, let me know and I'll re-open.

**Comment by johndturn** [comment]
TBH, after reviewing your screenshot I'm not sure if it's feasible to list out all of those backups, but admittedly I haven't seen that before. I use Time machine as well and I don't see those volumes showing up. So maybe the feature referenced above at least is a starting point? 

At some point maybe allowing for an Ignore Regex or something might be beneficial.
